AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Bouncer v3.0.0 - Clawdbot AWS 命令審批執行系統 (API Gateway)

Parameters:
  Environment:
    Type: String
    Default: "prod"
    Description: 環境名稱（prod/dev/staging），用於資源名稱前綴
  TelegramBotToken:
    Type: String
    NoEcho: true
    Description: 審批專用 Telegram Bot Token
  ApprovedChatId:
    Type: String
    Default: ""
    Description: 允許審批的 Telegram Chat ID（支援多個，用逗號分隔，例如：999999999,-5177412711）
  RequestSecret:
    Type: String
    NoEcho: true
    Description: Clawdbot 請求時需要的 Secret
  TelegramWebhookSecret:
    Type: String
    NoEcho: true
    Description: Telegram Webhook 驗證 Secret（防偽造）
  EnableHmac:
    Type: String
    Default: "false"
    AllowedValues: ["true", "false"]
    Description: 啟用 HMAC 請求簽章驗證（Phase 2）
  McpMaxWait:
    Type: String
    Default: "30"
    Description: DEPRECATED - 不再用於 sync long-polling。保留作為 approval timeout 上限。
  DefaultAccountId:
    Type: String
    Default: ""
    Description: 預設 AWS 帳號 ID（用於上傳桶等資源，部署時必須指定）

Globals:
  Function:
    Timeout: 60
    Runtime: python3.12
    MemorySize: 256
    Architectures:
      - arm64
    Tracing: Active
    LoggingConfig:
      LogFormat: JSON

Resources:
  # ============================================================
  # DynamoDB - 待審批請求存儲
  # ============================================================
  RequestsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub "bouncer-${Environment}-requests"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: request_id
          AttributeType: S
        - AttributeName: source
          AttributeType: S
        - AttributeName: created_at
          AttributeType: N
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: request_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: source-created-index
          KeySchema:
            - AttributeName: source
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - status
        - IndexName: status-created-index
          KeySchema:
            - AttributeName: status
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Project
          Value: Bouncer
        - Key: auto-delete
          Value: "no"

  # ============================================================
  # DynamoDB - 帳號配置
  # ============================================================
  AccountsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub "bouncer-${Environment}-accounts"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: account_id
          AttributeType: S
      KeySchema:
        - AttributeName: account_id
          KeyType: HASH
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Project
          Value: Bouncer
        - Key: auto-delete
          Value: "no"

  # ============================================================
  # DynamoDB - 命令歷史記錄（序列分析用）
  # ============================================================
  CommandHistoryTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub "bouncer-${Environment}-command-history"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Project
          Value: Bouncer
        - Key: auto-delete
          Value: "no"

  # ============================================================
  # DynamoDB - Shadow Approval 記錄（智慧審批數據收集）
  # ============================================================
  ShadowApprovalsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: !Sub "bouncer-${Environment}-shadow-approvals"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: request_id
          AttributeType: S
      KeySchema:
        - AttributeName: request_id
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Project
          Value: Bouncer
        - Key: auto-delete
          Value: "no"
        - Key: Purpose
          Value: "Smart approval shadow mode data collection"

  # ============================================================
  # IAM - Default 帳號 BouncerRole（命令執行用）
  # Lambda assume 此 role 後執行 AWS CLI 命令
  # 與 cross-account BouncerRole 權限一致
  # ============================================================
  DefaultBouncerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: BouncerRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${AWS::AccountId}:root'
            Action: sts:AssumeRole
      Policies:
        - PolicyName: PowerUserAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: PowerUserAccess
                Effect: Allow
                Action: '*'
                Resource: '*'
              - Sid: DenyDangerousIAM
                Effect: Deny
                Action:
                  - iam:CreateUser
                  - iam:DeleteUser
                  - iam:AttachUserPolicy
                  - iam:DetachUserPolicy
                  - iam:PutUserPolicy
                  - iam:DeleteUserPolicy
                  - iam:CreateAccessKey
                  - iam:DeleteAccessKey
                  - iam:UpdateAccessKey
                  - iam:CreateLoginProfile
                  - iam:DeleteLoginProfile
                  - iam:UpdateLoginProfile
                  - iam:DeactivateMFADevice
                  - iam:DeleteVirtualMFADevice
                  - iam:CreatePolicy
                  - iam:CreatePolicyVersion
                  - iam:DeletePolicyVersion
                  - iam:SetDefaultPolicyVersion
                  - iam:AddRoleToInstanceProfile
                  - iam:CreateInstanceProfile
                  - iam:CreateServiceLinkedRole
                Resource: '*'
              - Sid: DenyOrganizations
                Effect: Deny
                Action:
                  - organizations:*
                Resource: '*'
              - Sid: DenySelfEscalation
                Effect: Deny
                Action:
                  - iam:UpdateAssumeRolePolicy
                  - iam:PutRolePolicy
                  - iam:DeleteRolePolicy
                  - iam:AttachRolePolicy
                  - iam:DetachRolePolicy
                  - iam:DeleteRole
                Resource: !Sub 'arn:aws:iam::${AWS::AccountId}:role/BouncerRole'
      Tags:
        - Key: Project
          Value: Bouncer
        - Key: auto-delete
          Value: "no"

  # ============================================================
  # Lambda - 主函數
  # ============================================================
  ApprovalFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "bouncer-${Environment}-function"
      CodeUri: src/
      Handler: app.lambda_handler
      Description: Bouncer v3.0.0 - AWS 命令審批執行
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt ApprovalFunctionDLQ.Arn
      Tags:
        Project: Bouncer
        auto-delete: "no"
      Events:
        RootPost:
          Type: Api
          Properties:
            RestApiId: !Ref BouncerApi
            Path: /
            Method: POST
        RootGet:
          Type: Api
          Properties:
            RestApiId: !Ref BouncerApi
            Path: /
            Method: GET
        Webhook:
          Type: Api
          Properties:
            RestApiId: !Ref BouncerApi
            Path: /webhook
            Method: POST
        Mcp:
          Type: Api
          Properties:
            RestApiId: !Ref BouncerApi
            Path: /mcp
            Method: POST
        Status:
          Type: Api
          Properties:
            RestApiId: !Ref BouncerApi
            Path: /status/{request_id}
            Method: GET
      Environment:
        Variables:
          TELEGRAM_BOT_TOKEN: !Ref TelegramBotToken
          APPROVED_CHAT_ID: !Ref ApprovedChatId
          REQUEST_SECRET: !Ref RequestSecret
          TELEGRAM_WEBHOOK_SECRET: !Ref TelegramWebhookSecret
          TABLE_NAME: !Ref RequestsTable
          ACCOUNTS_TABLE_NAME: !Ref AccountsTable
          COMMAND_HISTORY_TABLE: !Ref CommandHistoryTable
          SHADOW_TABLE: !Ref ShadowApprovalsTable
          ENABLE_HMAC: !Ref EnableHmac
          MCP_MAX_WAIT: !Ref McpMaxWait
          DEFAULT_ACCOUNT_ID: !Ref DefaultAccountId
          # Deployer 相關
          PROJECTS_TABLE: bouncer-projects
          HISTORY_TABLE: bouncer-deploy-history
          LOCKS_TABLE: bouncer-deploy-locks
          DEPLOY_STATE_MACHINE_ARN: !Sub 'arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:sam-deployer-workflow'
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref RequestsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref AccountsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref CommandHistoryTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ShadowApprovalsTable
        # Deployer tables
        - DynamoDBCrudPolicy:
            TableName: bouncer-projects
        - DynamoDBCrudPolicy:
            TableName: bouncer-deploy-history
        - DynamoDBCrudPolicy:
            TableName: bouncer-deploy-locks
        - Version: '2012-10-17'
          Statement:
            # Assume BouncerRole — 所有帳號都走 assume role 執行命令
            # 通配 * 允許新增帳號不用改 template；Application 層有 accounts 表白名單控管
            - Sid: AssumeBouncerRole
              Effect: Allow
              Action: sts:AssumeRole
              Resource:
                - !GetAtt DefaultBouncerRole.Arn
                - 'arn:aws:iam::*:role/BouncerRole'
            # Step Functions for deployer
            - Sid: StepFunctionsAccess
              Effect: Allow
              Action:
                - states:StartExecution
                - states:DescribeExecution
                - states:StopExecution
              Resource: !Sub 'arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:sam-deployer-workflow'

  # ============================================================
  # API Gateway
  # ============================================================
  BouncerApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "bouncer-${Environment}-api"
      StageName: prod
      Tags:
        Project: Bouncer
        auto-delete: "no"

  # ============================================================
  # CloudWatch Alarms
  # ============================================================
  HighErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "bouncer-${Environment}-high-error-rate"
      MetricName: Errors
      Namespace: AWS/Lambda
      Dimensions:
        - Name: FunctionName
          Value: !Ref ApprovalFunction
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlarmNotificationTopic
      OKActions:
        - !Ref AlarmNotificationTopic

  # ============================================================
  # SNS - Alarm Notifications
  # ============================================================
  AlarmNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${Environment}-bouncer-alarms"

  # ============================================================
  # CloudWatch Alarm - API Gateway 5xx
  # ============================================================
  ApiGateway5xxAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${Environment}-bouncer-api-5xx"
      MetricName: 5XXError
      Namespace: AWS/ApiGateway
      Dimensions:
        - Name: ApiName
          Value: !Ref BouncerApi
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref AlarmNotificationTopic

  # ============================================================
  # CloudWatch Alarm - Lambda Duration (approaching timeout)
  # ============================================================
  LambdaDurationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${Environment}-bouncer-slow-lambda"
      MetricName: Duration
      Namespace: AWS/Lambda
      Dimensions:
        - Name: FunctionName
          Value: !Ref ApprovalFunction
      ExtendedStatistic: p99
      Period: 300
      EvaluationPeriods: 1
      Threshold: 600000
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref AlarmNotificationTopic

  # ============================================================
  # SQS - Dead Letter Queue
  # ============================================================
  ApprovalFunctionDLQ:
    Type: AWS::SQS::Queue
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      QueueName: !Sub "${Environment}-bouncer-dlq"
      MessageRetentionPeriod: 1209600

  # ============================================================
  # CloudWatch Alarm - DLQ Depth (messages stuck in DLQ)
  # ============================================================
  DLQDepthAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: bouncer-dlq-depth
      AlarmDescription: Messages in DLQ - investigate failed Lambda invocations
      Namespace: AWS/SQS
      MetricName: ApproximateNumberOfMessagesVisible
      Dimensions:
        - Name: QueueName
          Value: !GetAtt ApprovalFunctionDLQ.QueueName
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref AlarmNotificationTopic
      TreatMissingData: notBreaching

  # ============================================================
  # CloudWatch Logs - Log Group with Retention
  # ============================================================
  # Note: Log group /aws/lambda/${ApprovalFunction} already exists
  # (auto-created by Lambda). Set retention manually or via CLI:
  # aws logs put-retention-policy --log-group-name /aws/lambda/bouncer-prod-function --retention-in-days 30

  # ============================================================
  # API Gateway - Usage Plan + Throttling
  # ============================================================
  ApiUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn: BouncerApiprodStage
    Properties:
      UsagePlanName: bouncer-throttle
      Throttle:
        BurstLimit: 50
        RateLimit: 10
      ApiStages:
        - ApiId: !Ref BouncerApi
          Stage: prod

Outputs:
  ApiUrl:
    Description: API Gateway URL（Clawdbot 用這個發請求）
    Value: !Sub "https://${BouncerApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
  McpEndpoint:
    Description: MCP JSON-RPC endpoint
    Value: !Sub "https://${BouncerApi}.execute-api.${AWS::Region}.amazonaws.com/prod/mcp"
  WebhookUrl:
    Description: Telegram Webhook URL
    Value: !Sub "https://${BouncerApi}.execute-api.${AWS::Region}.amazonaws.com/prod/webhook"
  StatusEndpoint:
    Description: 查詢請求狀態 endpoint
    Value: !Sub "https://${BouncerApi}.execute-api.${AWS::Region}.amazonaws.com/prod/status/{request_id}"
  TableName:
    Description: DynamoDB 表名
    Value: !Ref RequestsTable
  DefaultBouncerRoleArn:
    Description: Default 帳號 BouncerRole ARN（用於 accounts 表設定）
    Value: !GetAtt DefaultBouncerRole.Arn
