AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Bouncer v3.0.0 - Clawdbot AWS 命令審批執行系統 (API Gateway)

Parameters:
  Environment:
    Type: String
    Default: "prod"
    Description: 環境名稱（prod/dev/staging），用於資源名稱前綴
  TelegramBotToken:
    Type: String
    NoEcho: true
    Description: 審批專用 Telegram Bot Token
  ApprovedChatId:
    Type: String
    Default: "999999999"
    Description: 允許審批的 Telegram Chat ID（支援多個，用逗號分隔，例如：999999999,-5177412711）
  RequestSecret:
    Type: String
    NoEcho: true
    Description: Clawdbot 請求時需要的 Secret
  TelegramWebhookSecret:
    Type: String
    NoEcho: true
    Description: Telegram Webhook 驗證 Secret（防偽造）
  EnableHmac:
    Type: String
    Default: "false"
    AllowedValues: ["true", "false"]
    Description: 啟用 HMAC 請求簽章驗證（Phase 2）
  McpMaxWait:
    Type: String
    Default: "840"
    Description: MCP 模式最大等待時間（秒），預設 840（14分鐘）

Globals:
  Function:
    Timeout: 900
    Runtime: python3.9
    MemorySize: 256
    Architectures:
      - arm64
    LoggingConfig:
      LogFormat: JSON

Resources:
  # ============================================================
  # DynamoDB - 待審批請求存儲
  # ============================================================
  RequestsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "bouncer-${Environment}-requests"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: request_id
          AttributeType: S
        - AttributeName: source
          AttributeType: S
        - AttributeName: created_at
          AttributeType: N
      KeySchema:
        - AttributeName: request_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: source-created-index
          KeySchema:
            - AttributeName: source
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - status
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Project
          Value: Bouncer
        - Key: auto-delete
          Value: "no"

  # ============================================================
  # DynamoDB - 帳號配置
  # ============================================================
  AccountsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "bouncer-${Environment}-accounts"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: account_id
          AttributeType: S
      KeySchema:
        - AttributeName: account_id
          KeyType: HASH
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      Tags:
        - Key: Project
          Value: Bouncer
        - Key: auto-delete
          Value: "no"

  # ============================================================
  # Lambda - 主函數
  # ============================================================
  ApprovalFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "bouncer-${Environment}-function"
      CodeUri: src/
      Handler: app.lambda_handler
      Description: Bouncer v3.0.0 - AWS 命令審批執行
      Tags:
        Project: Bouncer
        auto-delete: "no"
      Events:
        RootPost:
          Type: Api
          Properties:
            RestApiId: !Ref BouncerApi
            Path: /
            Method: POST
        RootGet:
          Type: Api
          Properties:
            RestApiId: !Ref BouncerApi
            Path: /
            Method: GET
        Webhook:
          Type: Api
          Properties:
            RestApiId: !Ref BouncerApi
            Path: /webhook
            Method: POST
        Mcp:
          Type: Api
          Properties:
            RestApiId: !Ref BouncerApi
            Path: /mcp
            Method: POST
        Status:
          Type: Api
          Properties:
            RestApiId: !Ref BouncerApi
            Path: /status/{request_id}
            Method: GET
      Environment:
        Variables:
          TELEGRAM_BOT_TOKEN: !Ref TelegramBotToken
          APPROVED_CHAT_ID: !Ref ApprovedChatId
          REQUEST_SECRET: !Ref RequestSecret
          TELEGRAM_WEBHOOK_SECRET: !Ref TelegramWebhookSecret
          TABLE_NAME: !Ref RequestsTable
          ACCOUNTS_TABLE_NAME: !Ref AccountsTable
          ENABLE_HMAC: !Ref EnableHmac
          MCP_MAX_WAIT: !Ref McpMaxWait
          DEFAULT_ACCOUNT_ID: '111111111111'
          # Deployer 相關
          PROJECTS_TABLE: bouncer-projects
          HISTORY_TABLE: bouncer-deploy-history
          LOCKS_TABLE: bouncer-deploy-locks
          DEPLOY_STATE_MACHINE_ARN: arn:aws:states:us-east-1:111111111111:stateMachine:sam-deployer-workflow
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref RequestsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref AccountsTable
        # Deployer tables
        - DynamoDBCrudPolicy:
            TableName: bouncer-projects
        - DynamoDBCrudPolicy:
            TableName: bouncer-deploy-history
        - DynamoDBCrudPolicy:
            TableName: bouncer-deploy-locks
        - Version: '2012-10-17'
          Statement:
            # Step Functions for deployer
            - Sid: StepFunctionsAccess
              Effect: Allow
              Action:
                - states:StartExecution
                - states:DescribeExecution
                - states:StopExecution
              Resource: arn:aws:states:us-east-1:111111111111:stateMachine:sam-deployer-workflow
            # PowerUser: 可以做大部分事情，但不能動 IAM
            - Sid: PowerUserAccess
              Effect: Allow
              Action: '*'
              Resource: '*'
            - Sid: DenyDangerousIAM
              Effect: Deny
              Action:
                - iam:CreateUser
                - iam:DeleteUser
                - iam:CreateRole
                - iam:DeleteRole
                - iam:AttachUserPolicy
                - iam:DetachUserPolicy
                - iam:AttachRolePolicy
                - iam:DetachRolePolicy
                - iam:PutUserPolicy
                - iam:DeleteUserPolicy
                - iam:PutRolePolicy
                - iam:DeleteRolePolicy
                - iam:CreateAccessKey
                - iam:DeleteAccessKey
                - iam:UpdateAccessKey
                - organizations:*
              Resource: '*'

  # ============================================================
  # API Gateway
  # ============================================================
  BouncerApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "bouncer-${Environment}-api"
      StageName: prod
      Tags:
        Project: Bouncer
        auto-delete: "no"
      Cors:
        AllowOrigin: "'*'"
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Approval-Secret,X-Timestamp,X-Nonce,X-Signature'"

  # ============================================================
  # CloudWatch Alarms
  # ============================================================
  HighErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "bouncer-${Environment}-high-error-rate"
      MetricName: Errors
      Namespace: AWS/Lambda
      Dimensions:
        - Name: FunctionName
          Value: !Ref ApprovalFunction
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      TreatMissingData: notBreaching

Outputs:
  ApiUrl:
    Description: API Gateway URL（Clawdbot 用這個發請求）
    Value: !Sub "https://${BouncerApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
  McpEndpoint:
    Description: MCP JSON-RPC endpoint
    Value: !Sub "https://${BouncerApi}.execute-api.${AWS::Region}.amazonaws.com/prod/mcp"
  WebhookUrl:
    Description: Telegram Webhook URL
    Value: !Sub "https://${BouncerApi}.execute-api.${AWS::Region}.amazonaws.com/prod/webhook"
  StatusEndpoint:
    Description: 查詢請求狀態 endpoint
    Value: !Sub "https://${BouncerApi}.execute-api.${AWS::Region}.amazonaws.com/prod/status/{request_id}"
  TableName:
    Description: DynamoDB 表名
    Value: !Ref RequestsTable
