"""
Changeset Analyzer — Sprint 32-001a (refactored Sprint 73)

Provides changeset analysis and cleanup for determining whether a
CloudFormation deployment only changes Lambda function code (safe to
auto-approve).

As of Sprint 73, dry-run changeset creation is no longer needed here.
SAM deploy --no-execute-changeset creates the changeset in Phase 1
(CodeBuild), and this module only analyzes the pre-existing changeset.
"""
from __future__ import annotations

import time
from dataclasses import dataclass, field
from typing import Optional

import logging
from botocore.exceptions import ClientError

# aws_lambda_powertools not available in notifier Lambda — use stdlib logging
logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------


@dataclass
class AnalysisResult:
    """Result of a CloudFormation changeset analysis."""

    is_code_only: bool
    resource_changes: list  # raw CFN ResourceChange dicts
    error: Optional[str] = field(default=None)  # populated on analysis failure


# ---------------------------------------------------------------------------
# Pure logic
# ---------------------------------------------------------------------------


def is_code_only_change(result: AnalysisResult) -> bool:
    """Whitelist check: return True only when ALL conditions are met.

    Allowed resource changes (SAM AutoPublishAlias normal lifecycle):
    - AWS::Lambda::Function  Modify  → Code property change only
    - AWS::Lambda::Version   Add     → SAM publishes a new version
    - AWS::Lambda::Version   Delete  → SAM removes old version
    - AWS::Lambda::Alias     Modify  → Alias points to new version
    - AWS::Logs::LogGroup    Add     → SAM auto-creates log groups

    Any other resource type or action → False (fail-safe → human approval).
    Empty resource_changes → False (fail-safe: unexpected empty changeset
    should not bypass human approval).
    """
    # Condition 1 — analysis must have succeeded
    if result.error is not None:
        return False

    # Empty changeset → safe (no resource changes = no-op deploy)
    # Phase 1 already handles "No changes to deploy" via no_changes=true flag.
    # If changeset was created but has zero Changes[], it's also safe.
    if not result.resource_changes:
        return True

    # SAM AutoPublishAlias lifecycle types that are always safe
    # SAM lifecycle types that are always safe (auto-generated by SAM transform)
    _SAFE_LAMBDA_TYPES = {
        "AWS::Lambda::Version",
        "AWS::Lambda::Alias",
        "AWS::Lambda::Permission",        # SAM Events property generates permissions
        "AWS::Lambda::LayerVersion",       # Layer code update
    }

    # SAM auto-generated resource types — Modify is safe (SAM lifecycle)
    _SAFE_SAM_TYPES = {
        "AWS::ApiGateway::RestApi",
        "AWS::ApiGateway::Stage",
        "AWS::ApiGateway::Deployment",
        "AWS::ApiGateway::Method",
        "AWS::ApiGateway::Resource",
        "AWS::ApiGatewayV2::Api",
        "AWS::ApiGatewayV2::Stage",
        "AWS::ApiGatewayV2::Route",
        "AWS::ApiGatewayV2::Integration",
        "AWS::ApiGatewayV2::Authorizer",
        "AWS::Events::Rule",              # SAM Schedule/Event triggers
        "AWS::Scheduler::Schedule",        # SAM ScheduleV2
        "AWS::Scheduler::ScheduleGroup",
    }

    # Infrastructure types where Modify is safe (no IAM/delete risk)
    _SAFE_INFRA_MODIFY_TYPES = {
        "AWS::DynamoDB::Table",              # GSI/capacity/TTL changes
        "AWS::DynamoDB::GlobalTable",
        "AWS::CloudFront::Distribution",     # behavior/origin changes
        "AWS::S3::Bucket",                   # policy/lifecycle changes
        "AWS::S3::BucketPolicy",
        "AWS::WAFv2::WebACL",                # rule updates
        "AWS::WAFv2::RuleGroup",
        "AWS::CloudWatch::Alarm",            # threshold changes
        "AWS::CloudWatch::Dashboard",
        "AWS::SNS::Topic",
        "AWS::SNS::Subscription",
        "AWS::SQS::Queue",
    }

    # Resource types that SAM auto-creates and are safe to add
    _SAFE_ADD_TYPES = {
        "AWS::Logs::LogGroup",
    }

    for change in result.resource_changes:
        rc = change.get("ResourceChange", {})
        resource_type = rc.get("ResourceType", "")
        action = rc.get("Action", "")

        # Lambda Version/Alias/Permission and SAM lifecycle types — always safe
        if resource_type in _SAFE_LAMBDA_TYPES:
            continue

        # SAM auto-generated types (API GW, Events, Scheduler) — Modify is safe
        if resource_type in _SAFE_SAM_TYPES and action == "Modify":
            continue

        # SAM auto-created resources (e.g. LogGroup Add) are safe
        if resource_type in _SAFE_ADD_TYPES and action == "Add":
            continue

        # Infrastructure Modify (no Add/Delete) — safe for dev stacks
        if resource_type in _SAFE_INFRA_MODIFY_TYPES and action == "Modify":
            continue

        # IAM::Role Modify with Policies-only target is SAM lifecycle
        # (SAM-generated roles for schedulers/events contain Lambda ARN references
        #  that update when Lambda code changes. No actual IAM permission change.)
        if resource_type == "AWS::IAM::Role" and action == "Modify":
            details = rc.get("Details", [])
            targets = [d.get("Target", {}).get("Name", "") for d in details]
            if all(t == "Policies" for t in targets) and targets:
                continue  # safe: only Policies field changed

        # Custom resource Modify with ServiceToken-only target is SAM lifecycle
        # (ServiceToken = Lambda ARN; updates when Lambda code changes)
        if resource_type.startswith("Custom::") and action == "Modify":
            details = rc.get("Details", [])
            targets = [d.get("Target", {}).get("Name", "") for d in details]
            if targets == ["ServiceToken"]:
                continue

        # Lambda Function must be Modify-only
        if resource_type != "AWS::Lambda::Function":
            return False

        if action != "Modify":
            return False

        # All detail targets must be Properties.Code
        details = rc.get("Details", [])
        for detail in details:
            target = detail.get("Target", {})
            if target.get("Attribute") != "Properties":
                return False
            if target.get("Name") != "Code":
                return False

    return True


# ---------------------------------------------------------------------------
# CloudFormation helpers
# ---------------------------------------------------------------------------


def analyze_changeset(
    cfn_client,
    stack_name: str,
    changeset_name: str,
    max_wait: int = 60,
    poll_interval: int = 2,
) -> AnalysisResult:
    """Poll DescribeChangeSet until CREATE_COMPLETE, FAILED, or timeout.

    CREATE_COMPLETE → parse Changes[] → AnalysisResult
    FAILED          → AnalysisResult(is_code_only=False, resource_changes=[], error=status_reason)
    timeout         → AnalysisResult(is_code_only=False, resource_changes=[], error='timeout')
    """
    elapsed = 0

    while elapsed < max_wait:
        try:
            response = cfn_client.describe_change_set(
                StackName=stack_name,
                ChangeSetName=changeset_name,
            )
        except ClientError as e:
            error_msg = str(e)
            logger.error(
                "describe_changeset_error",
                extra={
                    "src_module": "changeset_analyzer",
                    "stack_name": stack_name,
                    "changeset_name": changeset_name,
                    "error": error_msg,
                },
            )
            return AnalysisResult(
                is_code_only=False,
                resource_changes=[],
                error=error_msg,
            )

        status = response.get("Status", "")
        status_reason = response.get("StatusReason", "")

        if status == "CREATE_COMPLETE":
            changes = response.get("Changes", [])
            result = AnalysisResult(
                is_code_only=False,  # will be computed by caller via is_code_only_change()
                resource_changes=changes,
            )
            result.is_code_only = is_code_only_change(result)
            logger.info(
                "changeset_analysis_complete",
                extra={
                    "src_module": "changeset_analyzer",
                    "stack_name": stack_name,
                    "changeset_name": changeset_name,
                    "change_count": len(changes),
                    "is_code_only": result.is_code_only,
                },
            )
            return result

        if status == "FAILED":
            logger.warning(
                "changeset_creation_failed",
                extra={
                    "src_module": "changeset_analyzer",
                    "stack_name": stack_name,
                    "changeset_name": changeset_name,
                    "status_reason": status_reason,
                },
            )
            return AnalysisResult(
                is_code_only=False,
                resource_changes=[],
                error=status_reason or "FAILED",
            )

        time.sleep(poll_interval)
        elapsed += poll_interval

    logger.warning(
        "changeset_analysis_timeout",
        extra={
            "src_module": "changeset_analyzer",
            "stack_name": stack_name,
            "changeset_name": changeset_name,
            "max_wait": max_wait,
        },
    )
    return AnalysisResult(
        is_code_only=False,
        resource_changes=[],
        error="timeout",
    )


def cleanup_changeset(
    cfn_client,
    stack_name: str,
    changeset_name: str,
) -> None:
    """Silently delete a changeset.

    ChangeSetNotFoundException → pass (already gone).
    Any other ClientError → log + pass (best-effort cleanup).
    """
    try:
        cfn_client.delete_change_set(
            StackName=stack_name,
            ChangeSetName=changeset_name,
        )
    except ClientError as e:
        code = e.response.get("Error", {}).get("Code", "")
        if code == "ChangeSetNotFoundException":
            return
        logger.warning(
            "cleanup_changeset_error",
            extra={
                "src_module": "changeset_analyzer",
                "stack_name": stack_name,
                "changeset_name": changeset_name,
                "error_code": code,
                "error": str(e),
            },
        )
# Sprint 33: SAM artifacts S3 permission added to Lambda role (2026-03-12)
# Sprint 33: DescribeStacks permission added (2026-03-12)
